apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gh-webhook
  namespace: default
spec:
  encryptedData:
    token: AgBX69hnNOBvS/4BhzhFUp9nsXdd1TDa+nRKWY/ozYbc1Gmp2iPMLt9ewGErXlLLoTPnWnAk/5+79vtQE89WjCGvINz3FFv/JZ9rJFDHyZIim9pvsotW7P8wM6cxZJXrccmp5YArUdwFZXFDQ3mgPfhVLHDXSmXkNsu4h9XSbofwT4YSTGGA1yhSXWcHmSZhf8M8ntRSuRt/s6mDn3PS0cvNe0XXfq2FStK1VWLBBdomtHs4C8L/jheUgLFYtOxN8j2ZXpZCcM+rf5Erp9XhBKeHP3ixRft4AYFcheid7EhzxTqOsBIB/dmU8mXJRPTz+1Tyl+4zcZHSidCIKZ61sqZ3QJ8CJQdNyrJA1gmZkfrdX7JtUhG9P2dwDQ0mgD1s93oN3M87U+kwjr5Fgpu4Z4oaP/aMTJXZ2DVwo1Hce1/vU0poOfAbT5b5CtAFEXods/x0r22UUuE62Fo/YDAoJkbmmQNIut0MdpZIG5TYmoZUV7dPxjpJWjA+EID4/grj+zaQUisto0/l+JKQ/sod1oWRNUT+8i+ckQri0ta6MCPbJl92xMdmEaEkU7SJ3vRRlIe9MWoI2nLJZJdUdeEP0NrXxIsO4zp4XsABuP/WjMLAdsqBbt/m7L+0Z9msBhqu/j8NP1SVHl5WYBCW8NC/Iy6Ad9tCdFFj3jqj9VbKCJR4gNq+OTJCqbMletFOwUgi0Rg2orDdMtC1A0dQShCwOVaQ2lKprWSptZE/xeu2DT5S1tPQUV1yqwGj
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gh-webhook
      namespace: default

