kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: gh-webhook-token
  namespace: default
  creationTimestamp:
spec:
  template:
    metadata:
      name: gh-webhook-token
      namespace: default
      creationTimestamp:
    data:
  encryptedData:
    token: AgCUH61e8COe9JwSs8jJJFuWJ+8WTGNSSfLbPVBq5DqnlaKp31Cd3XJaRZhBSe6UXh1Xi8TdXFzaZQ7KtlM7uGdWujByJiheRk2ctE1xaMo8qdF+VcobH5aI0tQqdQL5Y5nuLGuRsA0NUGn12cHipkhyVIMZ73ZnlbWX3NcGFymjdnbZaVGZG8rtGXTJ0F88rLGaoJ7ehUboWpIq3joHOj/L10tHNvhdQ3rasUdsJujV905wEXNKkQt5dJ74ArxVYOUQPI7ArMRAevleivupAd1WLCaELl7ZH8L2INNnf4KanV9kgepQLwuFvuj73MM78E8mI4xtywNC+1dIJuoQjaouho22uHSOnPZubY5ZJJM65iAcOF0/ETyS4nrh1pNtiC3HnUMmtOYxUw7kgPiWw64AuA78GK5bRG6wuML+LXhkY1pXph3mSr1AHq1XDzQRNGm1OG3BeEI55q7lhbxGaiWKoBYrCaXquY9V9I00G1AH54t8tqeJ2bLaRVzl967/TTLnNyQFol5pGdwz2nVncPDPMj2N6x+GudJD7YOv3JpQ+aGujgy8ruI8pJpTlNGYWbU319ksJ4HuX2BOUGpdS2FQR1pq6MhAlGtJzDwa7op2M5Y2uz2MSBKbEpYiFa60fR6TkOL/xDLdsvbKzbjDZXTMTD38//OEoMcsvPb9AlAw+6E9cY0SB7RrPjvh8405hHpBSiy07CFXRBCPmIsTdUoKD01sjrdXrb8SC/vA+WI=

