apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-events
resources:
- namespace.yaml
- gh-webhook-secret.yaml
- event-bus.yaml
- gh-webhook-events.yaml
- https://raw.githubusercontent.com/argoproj/argo-events/v1.6.1/manifests/install.yaml
